fix: updated the example to the vehicle database
chargetrip/examples pull request #130
Opened 2022-11-24 14:48 UTC by lsmienk

I updated the example to the new vehicle database. In order to test the updates you need to use the staging env. along with a valid x-client-id. 

- car -> vehicle
- range.real is no longer available
- availability of the vehicleList filter works differently and has been removed.

2022-12-09 15:00 UTC, Wouter125 requested changes

2022-12-12 09:17 UTC, lsmienk commented on examples/1.vehicles/2.vehicle-details/queries.js
> +    size: 5
That was not op purpose not sure why that happend. I will change this back.

2022-12-13 11:45 UTC, Wouter125 approved these changes

2022-12-13 11:45 UTC, Wouter125 commented on examples/1.vehicles/2.vehicle-details/queries.js
>      size: 12
```suggestion
    size: 20
```

2022-12-13 11:48 UTC, merged